ALTER TABLE `user_access_management`.`app_roles_permission` 
ADD COLUMN `Allow_Download` VARCHAR(1) NULL DEFAULT 'N' AFTER `Allow_Reassign`;

/*-----------------------*/
/*-----CUSTOMER-1145-----*/
/*-----------------------*/

INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Contact_Center_Agent','Agent','Notes','','Y','Y','N','N','N','N','N','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Contact_Center_Officer','Agent','Notes','','Y','Y','N','N','N','N','Y','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Contact_Center_Manager','Agent','Notes','','Y','Y','N','N','N','N','Y','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Operations_Manager','Agent','Notes','','Y','Y','N','N','N','N','Y','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('KYC_Officer','Agent','Notes','','N','N','N','N','N','N','N','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Settlement_Officer','Agent','Notes','','N','N','N','N','N','N','N','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Reconciliation_Officer','Agent','Notes','','N','N','N','N','N','N','N','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Chargeback_Officer','Agent','Notes','','N','N','N','N','N','N','N','Admin',NULL,NULL,'Y');

/*-----------------------*/
/*-----CUSTOMER-1136-----*/
/*-----------------------*/

INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Contact_Center_Agent','Customer','Notes','','Y','Y','N','N','N','N','N','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Contact_Center_Officer','Customer','Notes','','Y','Y','N','N','N','N','Y','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Contact_Center_Manager','Customer','Notes','','Y','Y','N','N','N','N','Y','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Operations_Manager','Customer','Notes','','Y','Y','N','N','N','N','Y','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('KYC_Officer','Customer','Notes','','N','N','N','N','N','N','N','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Settlement_Officer','Customer','Notes','','N','N','N','N','N','N','N','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Reconciliation_Officer','Customer','Notes','','N','N','N','N','N','N','N','Admin',NULL,NULL,'Y');
INSERT IGNORE INTO `user_access_management`.`app_roles_permission` (`Role`,`Module`,`SubModule`,`SubSubModule`,`Allow_Create`,`Allow_Read`,`Allow_Update`,`Allow_Close`,`Allow_Approve`,`Allow_Reassign`,`Allow_Download`,`Created_By`,`Updated_By`,`Updated_On`,`Is_Active`) VALUES ('Chargeback_Officer','Customer','Notes','','N','N','N','N','N','N','N','Admin',NULL,NULL,'Y');